#!/bin/bash
find src -type f -name "*.tsx" | while read -r file; do
  sed -i 's/bg-slate-900/bg-caval-dark/g' "$file"
  sed -i 's/bg-slate-800/bg-caval-dark\/90/g' "$file"
  sed -i 's/text-slate-900/text-caval-dark/g' "$file"
  sed -i 's/text-slate-600/text-caval-dark\/80/g' "$file"
  sed -i 's/text-slate-500/text-caval-dark\/60/g' "$file"
  sed -i 's/text-slate-400/text-caval-beige\/80/g' "$file"
  sed -i 's/text-slate-300/text-caval-beige/g' "$file"
  sed -i 's/bg-indigo-600/bg-caval-gold/g' "$file"
  sed -i 's/bg-indigo-500/bg-caval-gold/g' "$file"
  sed -i 's/text-indigo-600/text-caval-gold/g' "$file"
  sed -i 's/text-indigo-500/text-caval-gold/g' "$file"
  sed -i 's/text-indigo-400/text-caval-gold-light/g' "$file"
  sed -i 's/hover:bg-indigo-700/hover:bg-caval-gold-dark/g' "$file"
  sed -i 's/hover:bg-indigo-600/hover:bg-caval-gold/g' "$file"
  sed -i 's/hover:bg-indigo-500/hover:bg-caval-gold-light/g' "$file"
  sed -i 's/hover:text-indigo-600/hover:text-caval-gold/g' "$file"
  sed -i 's/bg-emerald-600/bg-caval-gold/g' "$file"
  sed -i 's/bg-emerald-500/bg-caval-gold/g' "$file"
  sed -i 's/bg-emerald-400/bg-caval-gold-light/g' "$file"
  sed -i 's/text-emerald-600/text-caval-gold/g' "$file"
  sed -i 's/text-emerald-500/text-caval-gold/g' "$file"
  sed -i 's/text-emerald-400/text-caval-gold-light/g' "$file"
  sed -i 's/hover:bg-emerald-500/hover:bg-caval-gold-light/g' "$file"
  sed -i 's/hover:bg-emerald-400/hover:bg-caval-gold-light/g' "$file"
  sed -i 's/bg-amber-500/bg-caval-gold/g' "$file"
  sed -i 's/bg-amber-400/bg-caval-gold-light/g' "$file"
  sed -i 's/text-amber-500/text-caval-gold/g' "$file"
  sed -i 's/text-amber-400/text-caval-gold-light/g' "$file"
  sed -i 's/hover:bg-amber-400/hover:bg-caval-gold-light/g' "$file"
  
  # Orbs and subtle backgrounds
  sed -i 's/bg-indigo-100/bg-caval-gold\/20/g' "$file"
  sed -i 's/bg-emerald-100/bg-caval-gold\/20/g' "$file"
  sed -i 's/bg-indigo-50\/50/bg-caval-gold\/5/g' "$file"
  sed -i 's/bg-slate-50\/85/bg-[#FAF8F5]\/85/g' "$file"
  sed -i 's/bg-slate-50/bg-[#FAF8F5]/g' "$file"
  sed -i 's/text-indigo-900/text-caval-gold-dark/g' "$file"
  sed -i 's/text-emerald-900/text-caval-gold-dark/g' "$file"
  sed -i 's/border-indigo-100/border-caval-gold\/20/g' "$file"
done
